name: Second workflow
on:
  push:
    branches:
      - "second-branch"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: echo "code was gotten"
      - name: Print goodbye
        run: echo "godbye"
